### ISSUE TITLE
Check for auth token before making changes

### ISSUE THREAD

**Issue by mrerberg** [Makvagabo/updatorio#2]
In [main.ts](https://github.com/Makvagabo/updatorio/blob/master/src/main.ts) there is code:

```ts
await makeBackup(modsFiles, options);

  removeMods(currentModsList, modsAvailableForUpdate, options);

  const authToken = await getAuthToken(options);

  await downloadMods(modsAvailableForUpdate, options, authToken);
```

I think that it would be better to check for auth token before any manipulations with files. For example, if auth request fails you did backups and removed modes for nothing. You should get auth token as a first step

**Comment by Makvagabo** [comment]
I agree, thanks!
